[project]
name = "gym-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.17.2",
    "fastapi>=0.127.0",
    "psycopg2-binary>=2.9.11",
    "sqlmodel>=0.0.29",
    "uvicorn>=0.40.0",
]
